backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Cats'
          name: "cats"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Kitty Image", name: "thumbnail", widget: "image"}            
            - { label: "Description", name: "description", widget: "text"}
  - name: "posts"
    label: "Posts"
    files:
    - label: "Post"
      name: "post"
      folder: "/content/posts"
      slug: {{slug}}
      create: true
      fields:
       - {label: "Title", name: "title", widget: "string"}
       - {label: "Publish Date", name: "date", widget: "datetime"}
       - {label: "Description", name: "description", widget: "text"}
       - {label: "Kittie Image", name: "thumbnail", widget: "image"}
       - {label: "Body", name: "body", widget: "markdown"}